Repository KB-Hackathon/BE, pull requests merged in 2025-09, with the labels that each got.

#7 [feat] 카프카 기본 설정 추가 및 에러 핸들러 수정
  build.gradle
  src/main/java/hackathon/kb/chakchak/global/exception/exceptions/BusinessException.java
  src/main/java/hackathon/kb/chakchak/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/hackathon/kb/chakchak/global/health/check/HealthCheckController.java
  src/main/java/hackathon/kb/chakchak/global/kafka/config/KafkaProducerConfig.java
  src/main/java/hackathon/kb/chakchak/global/kafka/dto/Common.java
  src/main/java/hackathon/kb/chakchak/global/kafka/dto/LogLevel.java
  src/main/java/hackathon/kb/chakchak/global/kafka/dto/LogMessage.java
  src/main/java/hackathon/kb/chakchak/global/kafka/producer/KafkaProducer.java
  src/main/java/hackathon/kb/chakchak/global/kafka/util/LogMessageMapper.java
  src/main/resources/application.yml
Labels: enhancement, feature, refactor

#11 [feat] openai 연동 - 상품 사진과 글로 하나의 줄글 생성
  build.gradle
  src/main/java/hackathon/kb/chakchak/domain/product/api/controller/ProductController.java
  src/main/java/hackathon/kb/chakchak/domain/product/service/OpenAIMultimodalNarrativeService.java
  src/main/java/hackathon/kb/chakchak/global/httpclient/HttpClientConfig.java
  src/main/resources/application.yml
Labels: enhancement, feature

#15 [Feat] swagger 기본 세팅 추가
  build.gradle
  src/main/resources/application.yml
Labels: enhancement, feature

#14 [feat] kakao 회원가입 및 로그인
  build.gradle
  src/main/java/hackathon/kb/chakchak/domain/auth/MemberPrincipal.java
  src/main/java/hackathon/kb/chakchak/domain/auth/api/controller/OauthController.java
  src/main/java/hackathon/kb/chakchak/domain/auth/service/AuthService.java
  src/main/java/hackathon/kb/chakchak/domain/auth/service/dto/SignupTokens.java
  src/main/java/hackathon/kb/chakchak/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/hackathon/kb/chakchak/domain/jwt/filter/JwtErrorCode.java
  src/main/java/hackathon/kb/chakchak/domain/jwt/util/CookieIssuer.java
  src/main/java/hackathon/kb/chakchak/domain/jwt/util/JwtIssuer.java
  src/main/java/hackathon/kb/chakchak/domain/member/api/controller/AuthController.java
  src/main/java/hackathon/kb/chakchak/domain/member/api/controller/MemberController.java
  src/main/java/hackathon/kb/chakchak/domain/member/api/dto/req/AdditionalInfoRequest.java
  src/main/java/hackathon/kb/chakchak/domain/member/api/dto/res/MemberProfileResponse.java
  src/main/java/hackathon/kb/chakchak/domain/member/domain/entity/Member.java
  src/main/java/hackathon/kb/chakchak/domain/member/repository/MemberRepository.java
  src/main/java/hackathon/kb/chakchak/domain/member/service/MemberService.java
  src/main/java/hackathon/kb/chakchak/global/entity/BaseEntity.java
  src/main/java/hackathon/kb/chakchak/global/ouath/kakao/service/KakaoOAuth2UserService.java
  src/main/java/hackathon/kb/chakchak/global/response/ResponseCode.java
  src/main/java/hackathon/kb/chakchak/global/security/CustomKakaoOAuth2User.java
  src/main/java/hackathon/kb/chakchak/global/security/config/SecurityConfig.java
  src/main/java/hackathon/kb/chakchak/global/security/handler/JsonAccessDeniedHandler.java
  src/main/java/hackathon/kb/chakchak/global/security/handler/JsonAuthenticationEntryPoint.java
  src/main/java/hackathon/kb/chakchak/global/security/handler/OAuth2FailureHandler.java
  src/main/java/hackathon/kb/chakchak/global/security/handler/OAuth2SuccessHandler.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement, feature

#19 [feature] s3 기본 세팅
  build.gradle
  src/main/java/hackathon/kb/chakchak/global/response/ResponseCode.java
  src/main/java/hackathon/kb/chakchak/global/s3/S3Controller.java
  src/main/java/hackathon/kb/chakchak/global/s3/config/S3Config.java
  src/main/java/hackathon/kb/chakchak/global/s3/service/S3StorageService.java
  src/main/resources/application.yml
Labels: feature

#18 [feature] 사업자 정보 조회와 행정동 코드 기능 연결
  src/main/java/hackathon/kb/chakchak/domain/member/domain/entity/Seller.java
  src/main/java/hackathon/kb/chakchak/domain/member/repository/MemberRepository.java
  src/main/java/hackathon/kb/chakchak/domain/member/service/MemberRolePromotionService.java
  src/main/java/hackathon/kb/chakchak/domain/member/service/SellerService.java
  src/main/java/hackathon/kb/chakchak/global/utils/api/juso/JusoApiClient.java
  src/main/resources/application.yml
Labels: enhancement, feature

#23 [feature] 쿠폰 주문 기능 추가
  src/main/java/hackathon/kb/chakchak/domain/member/api/controller/CouponController.java
  src/main/java/hackathon/kb/chakchak/domain/member/domain/dto/CouponInfo.java
  src/main/java/hackathon/kb/chakchak/domain/member/service/MemberCouponService.java
  src/main/java/hackathon/kb/chakchak/domain/order/api/controller/OrderController.java
  src/main/java/hackathon/kb/chakchak/domain/order/api/dto/req/CouponOrderReq.java
  src/main/java/hackathon/kb/chakchak/domain/order/api/dto/res/CouponOrderRes.java
  src/main/java/hackathon/kb/chakchak/domain/order/domain/entity/Coupon.java
  src/main/java/hackathon/kb/chakchak/domain/order/domain/entity/Order.java
  src/main/java/hackathon/kb/chakchak/domain/order/repository/CouponRepository.java
  src/main/java/hackathon/kb/chakchak/domain/order/repository/OrderRepository.java
  src/main/java/hackathon/kb/chakchak/domain/order/service/OrderService.java
  src/main/java/hackathon/kb/chakchak/domain/product/domain/entity/Image.java
  src/main/java/hackathon/kb/chakchak/domain/product/domain/entity/Tag.java
  src/main/java/hackathon/kb/chakchak/domain/product/repository/ProductRepository.java
  src/main/java/hackathon/kb/chakchak/global/response/ResponseCode.java
Labels: feature

#33 [fix] 로그인 응답 변경
  src/main/java/hackathon/kb/chakchak/domain/auth/api/controller/AuthController.java
  src/main/java/hackathon/kb/chakchak/domain/auth/api/controller/OauthController.java
  src/main/java/hackathon/kb/chakchak/domain/member/api/dto/req/AdditionalInfoRequest.java
  src/main/java/hackathon/kb/chakchak/domain/member/service/MemberService.java
  src/main/java/hackathon/kb/chakchak/global/security/config/SecurityConfig.java
  src/main/java/hackathon/kb/chakchak/global/security/handler/OAuth2SuccessHandler.java
  src/main/resources/application.yml
Labels: refactor

#36 [feature] report 관련 엔티티 생성
  src/main/java/hackathon/kb/chakchak/domain/member/api/controller/SellerController.java
  src/main/java/hackathon/kb/chakchak/domain/member/api/dto/req/BizRegisterRequest.java
  src/main/java/hackathon/kb/chakchak/domain/member/api/dto/res/BizRegisterResponse.java
  src/main/java/hackathon/kb/chakchak/domain/member/domain/entity/Buyer.java
  src/main/java/hackathon/kb/chakchak/domain/member/domain/entity/Member.java
  src/main/java/hackathon/kb/chakchak/domain/member/domain/entity/Seller.java
  src/main/java/hackathon/kb/chakchak/domain/report/domain/entity/Report.java
  src/main/java/hackathon/kb/chakchak/domain/report/repository/ReportRepository.java
  src/main/java/hackathon/kb/chakchak/domain/review/domain/entity/Review.java
  src/main/resources/application.properties
Labels: enhancement, feature

#42 [feat] option별 상품글 조회
  src/main/java/hackathon/kb/chakchak/domain/product/api/controller/ProductController.java
  src/main/java/hackathon/kb/chakchak/domain/product/repository/ProductRepository.java
  src/main/java/hackathon/kb/chakchak/domain/product/service/ProductBasicService.java
Labels: feature

#47 [feature] seller 조회
  src/main/java/hackathon/kb/chakchak/domain/member/api/controller/SellerController.java
  src/main/java/hackathon/kb/chakchak/domain/member/api/dto/req/BizRegisterRequest.java
  src/main/java/hackathon/kb/chakchak/domain/member/api/dto/res/SellerReadResponseDto.java
  src/main/java/hackathon/kb/chakchak/domain/member/repository/SellerRepository.java
  src/main/java/hackathon/kb/chakchak/domain/member/service/SellerBasicService.java
  src/main/java/hackathon/kb/chakchak/domain/product/api/controller/ProductController.java
  src/main/java/hackathon/kb/chakchak/domain/product/domain/dto/ProductReadResponseDto.java
  src/main/java/hackathon/kb/chakchak/domain/product/domain/dto/ProductSimpleResponseDto.java
  src/main/java/hackathon/kb/chakchak/domain/product/util/ProductToDtoMapper.java
  src/main/java/hackathon/kb/chakchak/global/exception/exceptions/BusinessException.java
  src/main/java/hackathon/kb/chakchak/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/hackathon/kb/chakchak/global/response/BaseResponse.java
  src/main/java/hackathon/kb/chakchak/global/response/ResponseCode.java
Labels: feature, refactor

#49 [feature] 마이페이지 - buyer 참여중인 공구 및 완료된 공구 조회
  src/main/java/hackathon/kb/chakchak/domain/member/api/controller/BuyerController.java
  src/main/java/hackathon/kb/chakchak/domain/member/api/dto/res/BuyerOrderListResponse.java
  src/main/java/hackathon/kb/chakchak/domain/member/domain/dto/BuyerReadResponseDto.java
  src/main/java/hackathon/kb/chakchak/domain/member/service/BuyerService.java
  src/main/java/hackathon/kb/chakchak/domain/member/service/MemberService.java
  src/main/java/hackathon/kb/chakchak/domain/order/domain/dto/OrderResponseDto.java
  src/main/java/hackathon/kb/chakchak/domain/order/domain/entity/Order.java
  src/main/java/hackathon/kb/chakchak/domain/order/repository/OrderRepository.java
  src/main/java/hackathon/kb/chakchak/domain/product/api/controller/ProductController.java
  src/main/java/hackathon/kb/chakchak/domain/product/api/dto/ProductProgressResponseDto.java
  src/main/java/hackathon/kb/chakchak/domain/product/domain/dto/ProductPreviewResponseDto.java
  src/main/java/hackathon/kb/chakchak/domain/product/repository/ProductRepository.java
  src/main/java/hackathon/kb/chakchak/domain/product/service/ProductService.java
  src/main/java/hackathon/kb/chakchak/domain/product/util/ProductToDtoMapper.java
  src/main/java/hackathon/kb/chakchak/global/response/ResponseCode.java
Labels: feature

#48 [feature] 리포트 서비스 로직 구현
  src/main/java/hackathon/kb/chakchak/domain/report/api/controller/ReportController.java
  src/main/java/hackathon/kb/chakchak/domain/report/api/dto/ReportResponseDto.java
  src/main/java/hackathon/kb/chakchak/domain/report/domain/entity/Report.java
  src/main/java/hackathon/kb/chakchak/domain/report/service/ReportService.java
  src/main/java/hackathon/kb/chakchak/global/response/ResponseCode.java
Labels: enhancement, feature

#52 [Feat]: 차대변 회계 테이블 기본 엔티티 코드 작성
  src/main/java/hackathon/kb/chakchak/domain/ledger/entity/AccountType.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/entity/LedgerCode.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/entity/LedgerEntry.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/entity/LedgerType.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/entity/LedgerVoucher.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/entity/TransactionType.java
Labels: feature

#82 [feat] 차대변 테이블 정합성 검증 코드 작성
  build.gradle
  src/main/java/hackathon/kb/chakchak/ChakchakApplication.java
  src/main/java/hackathon/kb/chakchak/domain/escrow/domain/entity/Escrow.java
  src/main/java/hackathon/kb/chakchak/domain/escrow/domain/repository/EscrowRepositoryJun.java
  src/main/java/hackathon/kb/chakchak/domain/escrow/domain/service/EscrowServiceJun.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/batch/config/LedgerBatchConfig.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/batch/controller/LedgerJobController.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/batch/processor/LedgerProcessorConfig.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/batch/reader/IdRangePartitioner.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/batch/reader/LedgerReader.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/batch/scheduler/LedgerJobScheduler.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/batch/writer/LedgerWriter.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/entity/LedgerEntry.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/repository/LedgerRepository.java
  src/main/java/hackathon/kb/chakchak/domain/ledger/service/LedgerService.java
  src/main/java/hackathon/kb/chakchak/domain/order/repository/OrderRepository.java
  src/main/java/hackathon/kb/chakchak/domain/order/service/OrderService.java
  src/main/java/hackathon/kb/chakchak/domain/product/domain/entity/Product.java
  src/main/java/hackathon/kb/chakchak/domain/product/service/ProductNarrativeService.java
  src/main/java/hackathon/kb/chakchak/global/response/ResponseCode.java
  src/main/resources/application.yml
Labels: feature
